server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccination_center_db
    password: 9952625052
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: VACCINATION-CENTER-SERVICE